/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScanRow {
  port: number
  pid: number
  name?: string
  path?: string
  cmd?: string
  cwd?: string
  start?: string
}
export declare function scanListeningPorts(): Array<ScanRow>
